[package]
name = "databasecouch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
couch_rs = "0.8.36"
tokio = { version = "1.16.1", features = ["full"] }