[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-files = "0.6.0"
#TODO: instead use the latest stable maud version when avalaible
maud = { git="https://github.com/lambda-fairy/maud.git", rev="e6787cd62165a075c7f16a32f8bbacc398f52d13", features=["actix-web"] }
clap = { version="3", features=["derive"] }
#TODO: get rid of this safe_join
safe_join = { git = "https://github.com/marius851000/safe_join_mirror.git", rev="3f541a0222685f45b816a80664bb84ed825b93df"}
comrak = "0.12.1"
pmd_hack_storage = { path = "../storage" }
qstring = "0.7.2"
database = { path = "../database" }
tokio = { version = "1.16.1", features = ["full"] }
mime = "0.3.16"