[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maud = { version="0.23.0", features=["actix-web"] }
actix-web = "3"
clap = { version="3", features=["derive"] }
actix-files = "0.6.0"
#TODO: get rid of this safe_join
safe_join = { git = "https://github.com/marius851000/safe_join_mirror.git", rev="3f541a0222685f45b816a80664bb84ed825b93df"}
comrak = "0.12.1"
pmd_hack_storage = { path = "../storage" }
qstring = "0.7.2"