[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maud = { version="0.23.0", features=["actix-web"] }
actix-web = "3"
clap = "3.0.0-beta.5"
actix-files = "0.5.0"
safe_join = { git = "https://github.com/trailofbits/safe_join.git", rev="40ca21f70bd430a3f7352f231a83bdbc7ee37738"}
comrak = "0.12.1"
pmd_hack_storage = { path = "../storage" }